//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialPlanDetail
    {
        public int financialPlanDetailID { get; set; }
        public Nullable<int> financialPlanID { get; set; }
        public Nullable<int> taskID { get; set; }
    
        public virtual FinancialPlan FinancialPlan { get; set; }
        public virtual Task Task { get; set; }
    }
}
