//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFinanceManagementEntities : DbContext
    {
        public dbFinanceManagementEntities()
            : base("name=dbFinanceManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analysis> Analyses { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Debt> Debts { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<FinancialPlan> FinancialPlans { get; set; }
        public virtual DbSet<FinancialPlanDetail> FinancialPlanDetails { get; set; }
        public virtual DbSet<IncomeSource> IncomeSources { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<RoleCateogry> RoleCateogries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
